sudo: required
services: 
  - docker


before_install:
  - docker build -t katiebvogel/docker-react -f Dockerfile.dev .

script:
#  - docker run katiebvogel/docker-react npm run test -- --coverage
   - docker run -e CI=true katiebvogel/docker-react npm run test